import { supabase } from './supabaseClient';

const DEFAULT_AVATAR = '\u{1F9D1}\u200D\u{1F393}';

const AUTH_STORAGE_KEYS = [
    'edu_ai_user_id',
    'edu_ai_profile',
    'edu_ai_streak',
];

export function normalizeStudentEmail(name = '') {
    return `${name.trim().toLowerCase().replace(/[^a-z0-9]/g, '')}@student.edu.ai`;
}

export function getStoredUserId() {
    return localStorage.getItem('edu_ai_user_id');
}

export function getStoredProfile() {
    try {
        const raw = localStorage.getItem('edu_ai_profile');
        return raw ? JSON.parse(raw) : null;
    } catch {
        return null;
    }
}

export function persistAuthProfile(profile) {
    if (!profile) return;
    // Store the auth user ID (user_id), NOT the auto-generated profiles.id
    const authUserId = profile.user_id || profile.id;
    if (authUserId) {
        localStorage.setItem('edu_ai_user_id', authUserId);
    }
    localStorage.setItem('edu_ai_profile', JSON.stringify(profile));
}

export function clearAuthStorage() {
    AUTH_STORAGE_KEYS.forEach((key) => {
        localStorage.removeItem(key);
    });
}

export async function getAuthSessionUser() {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
        console.warn('Failed to load auth session:', error.message);
        return null;
    }
    return data?.session?.user || null;
}

export async function fetchProfileByUserId(userId) {
    if (!userId) return null;

    // profiles.user_id holds the auth user ID (profiles.id is an auto-generated PK)
    const { data, error } = await supabase
        .from('profiles')
        .select('*')
        .eq('user_id', userId)
        .maybeSingle();

    if (error) {
        throw error;
    }

    return data;
}

function buildProfilePayload(userId, { name, avatar, gradeGroup }) {
    // user_id = auth user ID; `id` is auto-generated by the DB
    return {
        user_id: userId,
        full_name: name?.trim() || 'Student',
        grade_group: gradeGroup || '5-8',
        avatar_url: avatar || DEFAULT_AVATAR,
    };
}

async function createProfileRecord(userId, { name, avatar, gradeGroup }) {
    const payload = buildProfilePayload(userId, { name, avatar, gradeGroup });
    // onConflict: 'user_id' matches the UNIQUE constraint on profiles.user_id
    const { data, error } = await supabase
        .from('profiles')
        .upsert(payload, { onConflict: 'user_id' })
        .select()
        .single();

    if (error) {
        throw error;
    }

    return data;
}

// profileId = profiles.id (auto-generated UUID), because user_streaks.user_id → profiles.id
async function ensureInitialStreak(profileId) {
    if (!profileId) return;

    const today = new Date().toLocaleDateString('sv-SE');
    const { error } = await supabase.from('user_streaks').upsert(
        {
            user_id: profileId,
            current_streak: 1,
            longest_streak: 1,
            last_active_date: today,
            active_dates: [today],
            updated_at: new Date().toISOString(),
        },
        { onConflict: 'user_id' }
    );

    if (error) {
        console.warn('Failed to initialize user streak:', error.message);
    }
}

export async function signUpStudent({ name, email, password, avatar, gradeGroup }) {
    const safeEmail = email?.trim().toLowerCase();
    const safePassword = password?.trim() || `student-${Math.random().toString(36).slice(2, 10)}`;
    const profileMetadata = {
        full_name: name?.trim() || 'Student',
        grade_group: gradeGroup || '5-8',
        avatar_url: avatar || DEFAULT_AVATAR,
    };

    const { data: authData, error: authError } = await supabase.auth.signUp({
        email: safeEmail,
        password: safePassword,
        options: {
            data: profileMetadata,
        },
    });

    if (authError) {
        throw authError;
    }

    const userId = authData?.user?.id;
    if (!userId) {
        throw new Error('Supabase did not return a valid user id after signup.');
    }

    let profile = await fetchProfileByUserId(userId);

    if (!profile && authData.session) {
        profile = await createProfileRecord(userId, {
            name: profileMetadata.full_name,
            avatar: profileMetadata.avatar_url,
            gradeGroup: profileMetadata.grade_group,
        });
    }

    // When email confirmation is enabled, Supabase creates the auth user
    // without returning a session. The database trigger creates the profile,
    // but the app should wait for a real sign-in before caching auth locally.
    if (!profile) {
        profile = buildProfilePayload(userId, {
            name: profileMetadata.full_name,
            avatar: profileMetadata.avatar_url,
            gradeGroup: profileMetadata.grade_group,
        });
    }

    if (!authData.session) {
        return { user: authData.user, profile, needsEmailConfirmation: true };
    }

    // Pass profile.id (auto-UUID) — user_streaks.user_id FK → profiles.id
    await ensureInitialStreak(profile.id);
    persistAuthProfile(profile);

    return { user: authData.user, profile, needsEmailConfirmation: false };
}

export async function getOrCreateProfile({ name, avatar, gradeGroup = '1-4', password = null }) {
    const email = normalizeStudentEmail(name);
    const { profile } = await signUpStudent({ name, email, password, avatar, gradeGroup });
    return profile;
}

export async function signInStudent({ email, password }) {
    const safeEmail = email?.trim().toLowerCase();

    const { data: authData, error: authError } = await supabase.auth.signInWithPassword({
        email: safeEmail,
        password: password?.trim(),
    });

    if (authError) {
        throw authError;
    }

    const userId = authData?.user?.id;
    if (!userId) {
        throw new Error('Supabase did not return a valid user id after sign in.');
    }

    let profile = await fetchProfileByUserId(userId);
    if (!profile) {
        const metadata = authData.user.user_metadata || {};
        profile = await createProfileRecord(userId, {
            name: metadata.full_name || metadata.name || safeEmail?.split('@')[0] || 'Student',
            avatar: metadata.avatar_url || DEFAULT_AVATAR,
            gradeGroup: metadata.grade_group || '5-8',
        });
    }

    // Pass profile.id (auto-UUID) — user_streaks.user_id FK → profiles.id
    await ensureInitialStreak(profile.id);
    persistAuthProfile(profile);
    return { user: authData.user, profile };
}

export async function signOutStudent() {
    clearAuthStorage();
    const { error } = await supabase.auth.signOut();
    if (error) {
        console.warn('Supabase sign out failed:', error.message);
    }
    return { error };
}
